# Generated by Django 4.1.1 on 2022-09-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_pricing_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_pricing',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=1000000000, primary_key=True, serialize=False),
        ),
    ]
