# Generated by Django 4.1.1 on 2022-10-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_pricing_manager', '0002_alter_customer_pricing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_pricing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
