# Generated by Django 4.1.1 on 2022-09-19 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_pricing_manager', '0001_initial'),
        ('customer_manager', '0002_customer_delete_company'),
        ('item_manager', '0004_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.DecimalField(decimal_places=0, max_digits=20)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('item_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('invoice_total', models.CharField(max_length=60)),
                ('invoice_age', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('invoice_paid', models.BooleanField(default=False)),
                ('invoice_customer_check_number', models.CharField(max_length=60)),
                ('customer_po', models.CharField(max_length=60)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_manager.customer')),
                ('customer_pricing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_pricing_manager.customer_pricing')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_manager.item')),
            ],
        ),
    ]
