# Generated by Django 4.1.1 on 2022-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0006_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_po',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_name_row_1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_name_row_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_name_row_3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_name_row_4',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_name_row_5',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_num_row_1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_num_row_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_num_row_3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_num_row_4',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_num_row_5',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_ea_row_1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_ea_row_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_ea_row_3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_ea_row_4',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_ea_row_5',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_freight_amount',
            field=models.CharField(default='00000', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_sales_amount',
            field=models.CharField(default='00000', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_total_due',
            field=models.CharField(default='00000', max_length=60),
        ),
    ]
