# Generated by Django 4.1.1 on 2022-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0008_invoice_customer_pricing_id_row_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_pricing_id_row_1',
            new_name='customer_pricing_ea_row_1',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_pricing_id_row_2',
            new_name='customer_pricing_ea_row_2',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_pricing_id_row_3',
            new_name='customer_pricing_ea_row_3',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_pricing_id_row_4',
            new_name='customer_pricing_ea_row_4',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_pricing_id_row_5',
            new_name='customer_pricing_ea_row_5',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='item_id_row_1',
            new_name='item_name_row_1',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='item_id_row_2',
            new_name='item_name_row_2',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='item_id_row_3',
            new_name='item_name_row_3',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='item_id_row_4',
            new_name='item_name_row_4',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='item_id_row_5',
            new_name='item_name_row_5',
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_num_row_1',
            field=models.CharField(default='00000', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_num_row_2',
            field=models.CharField(default='00000', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_num_row_3',
            field=models.CharField(default='00000', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_num_row_4',
            field=models.CharField(default='00000', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_num_row_5',
            field=models.CharField(default='00000', max_length=60),
        ),
    ]
