# Generated by Django 4.1.1 on 2022-09-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000000000),
            preserve_default=False,
        ),
    ]
