# Generated by Django 4.1.1 on 2022-09-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0004_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
