# Generated by Django 4.1.1 on 2022-09-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0004_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=1000000000, primary_key=True, serialize=False),
        ),
    ]
